version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    working_dir: /workspace/projetPhp

    volumes:
      - .:/workspace

    ports:
      - "8000:80"

  mysql:
    image: mysql:8.4

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest

    restart: unless-stopped

    depends_on:
      - mysql

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root

    ports:
      - "8080:80"

volumes:
  mysql-data:
